services:
  - type: web
    name: portfolio-v2
    env: docker
    plan: free # Можно поменять на starter ($7/мес) для большей скорости и без "засыпания"
    branch: main # Ветка, за которой следит Render
    healthCheckPath: /
    autoDeploy: true # ДА, это включает авто-деплой при каждом коммите!
